### ISSUE TITLE
SyntaxError: Unexpected reserved word when importing elements from example project

### ISSUE THREAD

**Issue by anback** [mikaelvesavuori/figmagic#53] opened 2020-09-11 13:08 UTC
When importing elements from figmagic example project we get the following error message: 

![image](https://user-images.githubusercontent.com/2440382/92929152-63f05300-f440-11ea-943a-2f7fb6c3f436.png)

Here is our figma json attached. 

Error message is really not explicit. maybe this issue is about producing a better error message. plz advice

Using the master branch and node version 12.14

**Comment by mikaelvesavuori** [comment] 2020-09-11 13:20
Interesting. I will see how I can troubleshoot this. I'm kind of putting down version 3 for now, as I am finishing the fairly big migration to Typescript coming in version 4. 

Note that the error itself is not output through Figmagic. "Unexpected reserved word" makes me thing maybe your component(s) has a named that is reserved in JS? Weird, but who knows.

Keeping this open, and I'll see what this is about.

**Comment by mikaelvesavuori** [comment] 2020-09-11 13:22
I see you changed title. Is this with figmagic-example? (https://github.com/mikaelvesavuori/figmagic-example)

**Comment by mikaelvesavuori** [comment] 2020-09-11 13:32
With a fresh `figmagic-example`I just verified basic functionality by:
* Fresh pull
* Install dependencies
* Rename `env` to `.env` and set your URL and token; you can copy a Figmagic template at `https://www.figma.com/community/file/821094451476848226/Figmagic-%E2%80%94-Design-System-for-Tokens`
* Create `.figmagicrc` and set `syncElements: true`
* Run `npm run figmagic`

No errors. Can you specify in more detail your current setup and how much you are doing "from scratch"?

**Comment by tomsoderlund** [comment] 2020-09-12 09:44
Hi @mikaelvesavuori, I work with @anback.

I just tried:

- Local install of figmagic@^3.0.23 (on node v13.12.0)
- `.env` with FIGMA_TOKEN, FIGMA_URL
- The default `.figmagicrc` from README but with `syncElements` and `syncGraphics` being true.
- Running with `node --experimental-modules ./node_modules/figmagic/index.mjs --syncGraphics --syncElements`

Design tokens are created just fine, but I get `SyntaxError: Unexpected reserved word` and no elements.

Output:

    $ node --experimental-modules ./node_modules/figmagic/index.mjs --syncGraphics --syncElements

    [33m
    Attempting to fetch data from Figma API...

    [33m
    Writing Figma base file...

    [33m
    Writing design tokens...

    [33m
    Attempting to parse elements...

    |||||
    |||||
    |||||
    |||||
    |||||
    |||||
    |||||
    |||||
    |||||
    * Form > Form
    |||||
    [
      {
        id: '3010:3',
        name: 'empty',
        visible: false,
        type: 'TEXT',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 274, y: 626, width: 78, height: 15 },
        constraints: { vertical: 'TOP', horizontal: 'LEFT' },
        fills: [ [Object] ],
        strokes: [],
        strokeWeight: 1,
        strokeAlign: 'OUTSIDE',
        effects: [],
        characters: 'asdf',
        style: {
          fontFamily: 'Helvetica Neue',
          fontPostScriptName: 'HelveticaNeue',
          fontWeight: 400,
          paragraphSpacing: 1,
          fontSize: 12,
          textAlignHorizontal: 'LEFT',
          textAlignVertical: 'CENTER',
          letterSpacing: 0,
          lineHeightPx: 14.0625,
          lineHeightPercent: 100,
          lineHeightUnit: 'INTRINSIC_%'
        },
        characterStyleOverrides: [],
        styleOverrideTable: {},
        styles: { text: '2875:20' }
      },
      {
        id: '3009:111',
        name: 'Normal',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 581, width: 32, height: 32 },
        preserveRatio: true,
        constraints: { vertical: 'CENTER', horizontal: 'CENTER' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 1,
        strokeAlign: 'INSIDE',
        effects: [],
        cornerRadius: 100,
        rectangleCornerRadii: [ 100, 100, 100, 100 ]
      }
    ]
    MAIN_ELEMENT {
      id: '3009:111',
      name: 'Normal',
      type: 'RECTANGLE',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: { x: 284, y: 581, width: 32, height: 32 },
      preserveRatio: true,
      constraints: { vertical: 'CENTER', horizontal: 'CENTER' },
      fills: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokes: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      effects: [],
      cornerRadius: 100,
      rectangleCornerRadii: [ 100, 100, 100, 100 ]
    }
    * Normal > Normal
    [
      {
        id: '3009:133',
        name: 'empty',
        visible: false,
        type: 'TEXT',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 274, y: 626, width: 78, height: 15 },
        constraints: { vertical: 'TOP', horizontal: 'LEFT' },
        fills: [ [Object] ],
        strokes: [],
        strokeWeight: 1,
        strokeAlign: 'OUTSIDE',
        effects: [],
        characters: 'asdf',
        style: {
          fontFamily: 'Helvetica Neue',
          fontPostScriptName: 'HelveticaNeue',
          fontWeight: 400,
          paragraphSpacing: 1,
          fontSize: 12,
          textAlignHorizontal: 'LEFT',
          textAlignVertical: 'CENTER',
          letterSpacing: 0,
          lineHeightPx: 14.0625,
          lineHeightPercent: 100,
          lineHeightUnit: 'INTRINSIC_%'
        },
        characterStyleOverrides: [],
        styleOverrideTable: {},
        styles: { text: '2875:20' }
      },
      {
        id: '3009:116',
        name: ':checked',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 581, width: 32, height: 32 },
        preserveRatio: true,
        constraints: { vertical: 'CENTER', horizontal: 'CENTER' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 1,
        strokeAlign: 'INSIDE',
        effects: [],
        cornerRadius: 100,
        rectangleCornerRadii: [ 100, 100, 100, 100 ]
      }
    ]
    MAIN_ELEMENT {
      id: '3009:116',
      name: ':checked',
      type: 'RECTANGLE',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: { x: 284, y: 581, width: 32, height: 32 },
      preserveRatio: true,
      constraints: { vertical: 'CENTER', horizontal: 'CENTER' },
      fills: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokes: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      effects: [],
      cornerRadius: 100,
      rectangleCornerRadii: [ 100, 100, 100, 100 ]
    }
    * :checked > :checked
    |||||
    * Slider > Slider
    |||||
    * HR > HR
    |||||
    |||||
    [
      {
        id: '2874:71',
        name: ':invalid',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 211, width: 320, height: 48 },
        constraints: { vertical: 'CENTER', horizontal: 'LEFT_RIGHT' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 2,
        strokeAlign: 'INSIDE',
        effects: [ [Object] ],
        styles: { effect: '2657:133' },
        cornerRadius: 4,
        rectangleCornerRadii: [ 4, 4, 4, 4 ]
      },
      {
        id: '3010:4',
        name: ':invalid',
        type: 'TEXT',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: {
          x: 300.0501708984375,
          y: 211,
          width: 287.899658203125,
          height: 48
        },
        constraints: { vertical: 'CENTER', horizontal: 'LEFT_RIGHT' },
        fills: [ [Object] ],
        strokes: [],
        strokeWeight: 1,
        strokeAlign: 'OUTSIDE',
        effects: [],
        characters: 'Sample input',
        style: {
          fontFamily: 'Helvetica Neue',
          fontPostScriptName: 'HelveticaNeue',
          fontWeight: 400,
          paragraphSpacing: 1,
          fontSize: 16,
          textAlignHorizontal: 'LEFT',
          textAlignVertical: 'CENTER',
          letterSpacing: 0,
          lineHeightPx: 18.75,
          lineHeightPercent: 100,
          lineHeightUnit: 'INTRINSIC_%'
        },
        characterStyleOverrides: [],
        styleOverrideTable: {},
        styles: { text: '2743:5' }
      }
    ]
    MAIN_ELEMENT {
      id: '2874:71',
      name: ':invalid',
      type: 'RECTANGLE',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: { x: 284, y: 211, width: 320, height: 48 },
      constraints: { vertical: 'CENTER', horizontal: 'LEFT_RIGHT' },
      fills: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokes: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokeWeight: 2,
      strokeAlign: 'INSIDE',
      effects: [
        {
          type: 'DROP_SHADOW',
          visible: true,
          color: [Object],
          blendMode: 'NORMAL',
          offset: [Object],
          radius: 5
        }
      ],
      styles: { effect: '2657:133' },
      cornerRadius: 4,
      rectangleCornerRadii: [ 4, 4, 4, 4 ]
    }
    * :invalid > :invalid
    [
      {
        id: '3010:20',
        name: ':placeholder',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 211, width: 320, height: 48 },
        constraints: { vertical: 'CENTER', horizontal: 'LEFT_RIGHT' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 2,
        strokeAlign: 'INSIDE',
        effects: [ [Object] ],
        styles: { effect: '2657:133' },
        cornerRadius: 4,
        rectangleCornerRadii: [ 4, 4, 4, 4 ]
      },
      {
        id: '3010:18',
        name: ':placeholder',
        type: 'TEXT',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: {
          x: 300.0501403808594,
          y: 211,
          width: 287.899658203125,
          height: 48
        },
        constraints: { vertical: 'CENTER', horizontal: 'LEFT_RIGHT' },
        fills: [ [Object] ],
        strokes: [],
        strokeWeight: 1,
        strokeAlign: 'OUTSIDE',
        effects: [],
        characters: 'Placeholder text',
        style: {
          fontFamily: 'Helvetica Neue',
          fontPostScriptName: 'HelveticaNeue',
          fontWeight: 400,
          paragraphSpacing: 1,
          fontSize: 16,
          textAlignHorizontal: 'LEFT',
          textAlignVertical: 'CENTER',
          letterSpacing: 0,
          lineHeightPx: 18.75,
          lineHeightPercent: 100,
          lineHeightUnit: 'INTRINSIC_%'
        },
        characterStyleOverrides: [],
        styleOverrideTable: {},
        styles: { text: '2743:5' }
      }
    ]
    MAIN_ELEMENT {
      id: '3010:20',
      name: ':placeholder',
      type: 'RECTANGLE',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: { x: 284, y: 211, width: 320, height: 48 },
      constraints: { vertical: 'CENTER', horizontal: 'LEFT_RIGHT' },
      fills: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokes: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokeWeight: 2,
      strokeAlign: 'INSIDE',
      effects: [
        {
          type: 'DROP_SHADOW',
          visible: true,
          color: [Object],
          blendMode: 'NORMAL',
          offset: [Object],
          radius: 5
        }
      ],
      styles: { effect: '2657:133' },
      cornerRadius: 4,
      rectangleCornerRadii: [ 4, 4, 4, 4 ]
    }
    * :placeholder > :placeholder
    [
      {
        id: '2874:36',
        name: 'Normal',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 211, width: 320, height: 48 },
        constraints: { vertical: 'CENTER', horizontal: 'LEFT_RIGHT' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 2,
        strokeAlign: 'INSIDE',
        effects: [ [Object] ],
        styles: { effect: '2657:133' },
        cornerRadius: 4,
        rectangleCornerRadii: [ 4, 4, 4, 4 ]
      },
      {
        id: '2874:38',
        name: 'Normal',
        type: 'TEXT',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: {
          x: 300.0501403808594,
          y: 211,
          width: 287.899658203125,
          height: 48
        },
        constraints: { vertical: 'CENTER', horizontal: 'LEFT_RIGHT' },
        fills: [ [Object] ],
        strokes: [],
        strokeWeight: 1,
        strokeAlign: 'OUTSIDE',
        effects: [],
        characters: 'Sample input',
        style: {
          fontFamily: 'Helvetica Neue',
          fontPostScriptName: 'HelveticaNeue',
          fontWeight: 400,
          paragraphSpacing: 1,
          fontSize: 16,
          textAlignHorizontal: 'LEFT',
          textAlignVertical: 'CENTER',
          letterSpacing: 0,
          lineHeightPx: 18.75,
          lineHeightPercent: 100,
          lineHeightUnit: 'INTRINSIC_%'
        },
        characterStyleOverrides: [],
        styleOverrideTable: {},
        styles: { text: '2743:5' }
      }
    ]
    MAIN_ELEMENT {
      id: '2874:36',
      name: 'Normal',
      type: 'RECTANGLE',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: { x: 284, y: 211, width: 320, height: 48 },
      constraints: { vertical: 'CENTER', horizontal: 'LEFT_RIGHT' },
      fills: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokes: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokeWeight: 2,
      strokeAlign: 'INSIDE',
      effects: [
        {
          type: 'DROP_SHADOW',
          visible: true,
          color: [Object],
          blendMode: 'NORMAL',
          offset: [Object],
          radius: 5
        }
      ],
      styles: { effect: '2657:133' },
      cornerRadius: 4,
      rectangleCornerRadii: [ 4, 4, 4, 4 ]
    }
    * Normal > Normal
    |||||
    [
      {
        id: '3005:95',
        name: '_:hover',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 1,
        strokeAlign: 'INSIDE',
        effects: [],
        cornerRadius: 8,
        rectangleCornerRadii: [ 8, 8, 8, 8 ]
      },
      {
        id: '3010:17',
        name: 'Error',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 1,
        strokeAlign: 'INSIDE',
        effects: [],
        cornerRadius: 8,
        rectangleCornerRadii: [ 8, 8, 8, 8 ]
      },
      {
        id: '3005:96',
        name: 'Error',
        type: 'TEXT',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [],
        strokeWeight: 1,
        strokeAlign: 'OUTSIDE',
        effects: [],
        characters: 'Error',
        style: {
          fontFamily: 'Helvetica Neue',
          fontPostScriptName: 'HelveticaNeue-Bold',
          fontWeight: 700,
          paragraphSpacing: 1,
          textCase: 'UPPER',
          fontSize: 16,
          textAlignHorizontal: 'CENTER',
          textAlignVertical: 'CENTER',
          letterSpacing: 0.8,
          lineHeightPx: 18.75,
          lineHeightPercent: 100,
          lineHeightUnit: 'INTRINSIC_%'
        },
        characterStyleOverrides: [],
        styleOverrideTable: {}
      }
    ]
    MAIN_ELEMENT {
      id: '3010:17',
      name: 'Error',
      type: 'RECTANGLE',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
      fills: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokes: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      effects: [],
      cornerRadius: 8,
      rectangleCornerRadii: [ 8, 8, 8, 8 ]
    }
    * Error > Error
    [
      {
        id: '3005:98',
        name: '_:hover',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 1,
        strokeAlign: 'INSIDE',
        effects: [],
        cornerRadius: 8,
        rectangleCornerRadii: [ 8, 8, 8, 8 ]
      },
      {
        id: '3010:16',
        name: 'Warning',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 1,
        strokeAlign: 'INSIDE',
        effects: [],
        cornerRadius: 8,
        rectangleCornerRadii: [ 8, 8, 8, 8 ]
      },
      {
        id: '3005:99',
        name: 'Warning',
        type: 'TEXT',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [],
        strokeWeight: 1,
        strokeAlign: 'OUTSIDE',
        effects: [],
        characters: 'Warning',
        style: {
          fontFamily: 'Helvetica Neue',
          fontPostScriptName: 'HelveticaNeue-Bold',
          fontWeight: 700,
          paragraphSpacing: 1,
          textCase: 'UPPER',
          fontSize: 16,
          textAlignHorizontal: 'CENTER',
          textAlignVertical: 'CENTER',
          letterSpacing: 0.8,
          lineHeightPx: 18.75,
          lineHeightPercent: 100,
          lineHeightUnit: 'INTRINSIC_%'
        },
        characterStyleOverrides: [],
        styleOverrideTable: {}
      }
    ]
    MAIN_ELEMENT {
      id: '3010:16',
      name: 'Warning',
      type: 'RECTANGLE',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
      fills: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokes: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      effects: [],
      cornerRadius: 8,
      rectangleCornerRadii: [ 8, 8, 8, 8 ]
    }
    * Warning > Warning
    [
      {
        id: '3005:101',
        name: '_:hover',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 1,
        strokeAlign: 'INSIDE',
        styles: { fill: '1:114' },
        effects: [],
        cornerRadius: 8,
        rectangleCornerRadii: [ 8, 8, 8, 8 ]
      },
      {
        id: '3013:3',
        name: '_:disabled',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 1,
        strokeAlign: 'INSIDE',
        styles: { fill: '1:102' },
        effects: [],
        cornerRadius: 8,
        rectangleCornerRadii: [ 8, 8, 8, 8 ]
      },
      {
        id: '3010:15',
        name: 'Normal',
        type: 'RECTANGLE',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [ [Object] ],
        strokeWeight: 1,
        strokeAlign: 'INSIDE',
        effects: [],
        cornerRadius: 8,
        rectangleCornerRadii: [ 8, 8, 8, 8 ]
      },
      {
        id: '3005:102',
        name: 'Normal',
        type: 'TEXT',
        blendMode: 'PASS_THROUGH',
        absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
        constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
        fills: [ [Object] ],
        strokes: [],
        strokeWeight: 1,
        strokeAlign: 'OUTSIDE',
        effects: [],
        characters: 'Normal',
        style: {
          fontFamily: 'Helvetica Neue',
          fontPostScriptName: 'HelveticaNeue-Bold',
          fontWeight: 700,
          paragraphSpacing: 1,
          textCase: 'UPPER',
          fontSize: 16,
          textAlignHorizontal: 'CENTER',
          textAlignVertical: 'CENTER',
          letterSpacing: 0.8,
          lineHeightPx: 18.75,
          lineHeightPercent: 100,
          lineHeightUnit: 'INTRINSIC_%'
        },
        characterStyleOverrides: [],
        styleOverrideTable: {}
      }
    ]
    MAIN_ELEMENT {
      id: '3010:15',
      name: 'Normal',
      type: 'RECTANGLE',
      blendMode: 'PASS_THROUGH',
      absoluteBoundingBox: { x: 284, y: 53, width: 320, height: 48 },
      constraints: { vertical: 'SCALE', horizontal: 'SCALE' },
      fills: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokes: [ { blendMode: 'NORMAL', type: 'SOLID', color: [Object] } ],
      strokeWeight: 1,
      strokeAlign: 'INSIDE',
      effects: [],
      cornerRadius: 8,
      rectangleCornerRadii: [ 8, 8, 8, 8 ]
    }
    * Normal > Normal
    SyntaxError: Unexpected reserved word
    Done in 2.87s.

**Comment by tomsoderlund** [comment] 2020-09-12 09:56
@mikaelvesavuori I added a try/catch to `figmagic/index.mjs` and got this clue:

    SyntaxError: Unexpected reserved word
      at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
      at async link (internal/modules/esm/module_job.js:37:21)

**Comment by mikaelvesavuori** [comment] 2020-09-12 11:40
Hey! I've done a small set of updates and pushed 3.0.24 now. However, none of that has any clear, 100% sure impact on the issue. The error comes from deeper inside Node, as previously stated. I did in fact get that same error on my first attempt, but it "magically" disappeared on the second run...?

The new version updates dependencies, removes the unnecessary console.log() messages and removes the `--experimental-modules` flag. Running locally in a freshly pulled Figmagic folder with requisite `.env`, I get full functionality using the Figma template, using Node 12.18.3, Node 13.14.0, and Node 14.8.0.

See if that improves your situation.

**Comment by tomsoderlund** [comment] 2020-09-12 12:10
Hi @mikaelvesavuori, thanks for the rapid response & action!

Unfortunately, I get the same error with 3.0.24 as before.

I also, _sometimes_, get this error (had same with 3.0.23):

    Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/MY_PROJECT_PATH/tokens/colors.mjs' imported from /MY_PROJECT_PATH/node_modules/figmagic/bin/functions/process/parseTypographyStylingFromElement.mjs

…but I think they’re unrelated.

**Comment by mikaelvesavuori** [comment] 2020-09-12 12:26
Too bad, but was worth a shot, if at least to update dependencies.

Tell me a bit about your current setup? Are you running within the Figmagic project, or are you using Figmagic as a dependency and running commands inside that project (as intended)?

One aspect I was reminded of now, since I am obviously not the typical consumer of Figmagic (rather, the producer), is that you need a folder of templates in your working directory (though, this does not seem to be your problem currently; but please verify).

There _are_ a couple of things that are poor about the version 3 implementation of the code you point to.
1. When refactoring, I saw that a lot of async stuff can in fact just be standard sync, reducing asynchronous errors, like file writes.
2. The `.mjs` file ending is hard coded and not actually dynamic, though you can write tokens to other formats than MJS. The code in 3.0.24 being:
```
const PATH = isTest ? path.join('testdata', 'tokens') : `tokens`;
const _colors = await import(path.join(`${process.cwd()}`, `${PATH}`, `colors.mjs`));
```

Both these should already have been handled in the on-going (unreleased) v4 work.

Summary: Based on the above, it smells like either this is an async problem or that you've specified another file format, thus not resolving the path.

**Comment by tomsoderlund** [comment] 2020-09-12 12:51
It sounds like it could be “folder of templates” problem, will check that out.

I created a blank project with `yarn init` and added Figmagic as dependency.

**Comment by tomsoderlund** [comment] 2020-09-12 12:56
P.S. @mikaelvesavuori Figmagic is such a game changer for UI development. I tried to make a Twitter shoutout that Figma should pay you to work on this but couldn’t find you on Twitter...

**Comment by mikaelvesavuori** [comment] 2020-09-12 13:02
Yeah, social media just ate so much time so I got rid of everything other than LinkedIn, years ago. I'd rather commit my spare time to open source than scroll all day! :) Much appreciated though, and I am always happy to hear from anyone using it. Feel free to hit me up if you are in the Göteborg area.

I am still continuing to see what I can possibly do in v3 before v4 drops, so keep nagging me if it ain't working.

**Comment by tomsoderlund** [comment] 2020-09-12 16:18
Sounds like smart priorities! Will certainly ping you when I’m in Göteborg.

Anyway, I changed the paths in `.figmagicrc`:

    "templates":{
      "templatePathReact":"./node_modules/figmagic/templates/react.jsx",
      "templatePathStyled":"./node_modules/figmagic/templates/styled.jsx",
      "templatePathStorybook":"./node_modules/figmagic/templates/story.js"
    }

…but still getting the “Unexpected reserved word”.

Complete `.figmagicrc`:

    {
      "debugMode":true,
      "fontUnit":"rem",
      "letterSpacingUnit":"em",
      "opacitiesUnit":"float",
      "outputTokenFormat":"mjs",
      "outputFileName":"figma.json",
      "outputFolderBaseFile":".figmagic",
      "outputFolderTokens":"tokens",
      "outputTokenDataType":"enum",
      "outputFolderElements":"elements",
      "outputFolderGraphics":"graphics",
      "outputFormatGraphics":"svg",
      "outputScaleGraphics":1,
      "recompileLocal":false,
      "remSize":16,
      "skipFileGeneration":{
        "skipReact":false,
        "skipStyled":false,
        "skipCss":false,
        "skipStorybook":false,
        "skipDescription":false,
        "forceUpdate":true
      },
      "spacingUnit":"rem",
      "syncElements":false,
      "syncGraphics":false,
      "templates":{
        "templatePathReact":"./node_modules/figmagic/templates/react.jsx",
        "templatePathStyled":"./node_modules/figmagic/templates/styled.jsx",
        "templatePathStorybook":"./node_modules/figmagic/templates/story.js"
      },
      "usePostscriptFontNames":false
    }

Will continue hunting...

**Comment by tomsoderlund** [comment] 2020-09-12 16:29
**Progress!** Using https://github.com/mikaelvesavuori/figmagic-example instead of my "from scratch" project manages to export Elements. Now trying to figure out what was missing in my project.

**Comment by mikaelvesavuori** [comment] 2020-09-12 16:39
Awesome! If you find what the diff was, I will be happy to improve docs for version 4.

**Comment by tomsoderlund** [comment] 2020-09-12 16:40
...and "solved"! Copying `.figmagicrc` from https://github.com/mikaelvesavuori/figmagic-example instead of using the one in the README https://github.com/mikaelvesavuori/figmagic#configuration-file-figmagicrc made it work.

Here’s the diff, I haven’t been able to figure out what caused the problem (it’s not `usePostscriptFontNames`):

<img width="1134" alt="figmagicrc_2_versions" src="https://user-images.githubusercontent.com/1368668/93000236-595cb900-f527-11ea-894f-95a02179f8d6.png">

**Comment by tomsoderlund** [comment] 2020-09-12 16:53
This is my current, minimalistic yet working `.figmagicrc`:

    {
      "outputTokenFormat": "mjs",
      "templates": {
        "templatePathReact": "./node_modules/figmagic/templates/react.jsx",
        "templatePathStyled": "./node_modules/figmagic/templates/styled.jsx",
        "templatePathStorybook": "./node_modules/figmagic/templates/story.js"
      }
    }

I tried changing `outputTokenFormat` to `js` but I get build errors referring to `mjs`, so maybe it’s hardcoded somewhere. No biggie.

**Comment by mikaelvesavuori** [comment] 2020-09-12 19:00
Cheers! Thanks for the update. Will have this in mind for v4. Closing since the issue is resolved.

Did a quick poke previously today on fixing the JS errors, but it's non-trivial enough that's I'll let that be fixed in the major release, instead of spending time fixing it now.

**Closed by mikaelvesavuori** 2020-09-12 19:00 UTC
