### ISSUE TITLE
Not ignoring nested frames with prefixes

### ISSUE THREAD

**Issue by davidbwaters** [mikaelvesavuori/figmagic#164] opened 2022-08-04 23:25 UTC
**Describe the bug**
Hi, since you added support for frame variants, it's not ignoring prefixed frames with the '_' or ':' prefixes

**Expected behavior**
These shouldn't be added to the output.

**Comment by mikaelvesavuori** [comment] 2022-08-05 04:58
I am not able to reproduce this. Are you using Figmagic `4.5.0`? Even the mixed-use messy example here works as intended.
<img width="575" alt="Screenshot 2022-08-05 at 06 58 03" src="https://user-images.githubusercontent.com/23580994/183004662-faad51c7-1cea-4275-b9dc-087193e43be3.png">

**Comment by mikaelvesavuori** [comment] 2022-08-05 04:59
Note that `:` is not an exclusion pattern, but a way to express text being text (i.e. root of element) and then, when used for frames/groups, for subclassing.

**Comment by davidbwaters** [comment] 2022-08-05 11:06
Sorry I updated the file with a workaround.  I'll post a fork with it how it was, but basically it's the button component's hidden icon with text layer.  When it's prefixed with an underscore, it still gets output with the underscore in the class name.

**Comment by mikaelvesavuori** [comment] 2022-08-05 12:32
I have indeed seen that elements prefixed with an underscore were not ignored. I will push that fix later.

**Comment by davidbwaters** [comment] 2022-08-05 13:17
Awesome, thanks!

**Comment by mikaelvesavuori** [comment] 2022-08-05 13:23
Let's close this one as there is nothing more to add here?

**Comment by davidbwaters** [comment] 2022-08-05 22:40
Hey, I'm still having the issue after the update.  This is the file you can test with.  It's the button element's _with-icon child. https://www.figma.com/file/cTi2jRPF169TxakM3pX6Dt/MTX-Figmagic-(Copy)?node-id=3914%3A9510

**Comment by mikaelvesavuori** [comment] 2022-08-06 05:32
I don't have permission to access the file.

**Comment by mikaelvesavuori** [comment] 2022-08-06 05:41
I am just toying a bit with what I already have and I am pretty sure I see the issue. Figmagic is hard-wired to support only a single level of nesting, so not only will not underscore exclusions not work, nothing else will either if it's not found in either the root _OR_ in the first-level frames/groups.

When I have access and can verify your new file with my statement.

**Comment by mikaelvesavuori** [comment] 2022-08-06 07:50
So what's become apparent is that the flat and nested elements code bases are pretty dissimilar and I'm reminded of how they really should not to be synced. I am attempting to bring them closer to each other. What you are seeing is that the deduplication done for nested elements is not done for your texts, meaning you end up with duplicate properties (prior dialog is still valid for certain cases, I believe).

**Comment by davidbwaters** [comment] 2022-08-08 02:49
sorry, I updated the sharing settings

**Comment by mikaelvesavuori** [comment] 2022-08-13 10:13
Hey again. Sorry for being late to this. Looking at the file, this is still a structural error in your file rather than with Figmagic itself. The "root" Button should not contain the variants, you will need to drag these into individual, independent frames/groups.

**Comment by mikaelvesavuori** [comment] 2022-08-20 08:08
I am ready to close this, if you are OK with it @davidbwaters and have verified that Figmagic is ignoring as per the expected pattern I have written about?

**Comment by mikaelvesavuori** [comment] 2022-09-08 15:01
Closing because of lack of activity

**Closed by mikaelvesavuori** 2022-09-08 15:01 UTC
Labels: wontfix, user-error
