### ISSUE TITLE
Design token paths aren't updated in Element CSS imports

### ISSUE THREAD

**Issue by MasterMahariel** [mikaelvesavuori/figmagic#99] opened 2021-03-23 06:06 UTC
**Describe the bug**
If you have a directory set for the `outputFolderTokens` key in `.figmagicrc` and have `syncElements` set to true, the design token import root paths for your element's CSS will be `tokens/` instead of the directory set in `outputFolderTokens`.

**To Reproduce**
1. Go to `.figmagicrc` in your project
2. Set `outputFolderTokens` to a custom location (I tried .figmagic/tokens)
3. Set `syncElements` to `true`
4. Go to the `elements` directory and open an element CSS file
5. Observe that the import path for design tokens is `tokens/`

***Bug Example***

In my `.figmagicrc`, I have ` "outputFolderTokens": ".figmagic/tokens"` but for my `CheckboxCSS.ts`, `import colors from 'tokens/colors'` was generated.

**Expected behavior**
If a `outputFolderTokens` value is set, the design token imports for the element CSS should use the outputFolderTokens value as its root path and if null, use `tokens` as the root path.

***Solution Example***

In my `.figmagicrc`, if I have ` "outputFolderTokens": ".figmagic/tokens"`, my `CheckboxCSS.ts` should show `import colors from '.figmagic/tokens/colors'`.

**Comment by mikaelvesavuori** [comment] 2021-03-23 08:23
This is now fixed in version `4.0.14`.

**Comment by MasterMahariel** [comment] 2021-03-23 15:21
Hi  @mikaelvesavuori!  Thanks for the update. I had updated and received version `4.0.15` and found that the paths look correct but I am getting an error about the import paths.

Here's an example:
`Cannot find module '.figmagic/tokens/colors' or its corresponding type declarations.ts(2307)`

Upon typing in an absolute path, it starts in my C drive rather than the root of the project.

Is it possible that a `baseUrl` or something similar to that hasn't been set to the project root?

**Comment by mikaelvesavuori** [comment] 2021-03-23 15:33
That has to do with how Node and your project setup resolves paths, and is not technically a Figmagic issue. Could you try `/.figmagic/tokens/colors` and see if that works for you?

**Comment by MasterMahariel** [comment] 2021-03-23 15:42
It did not work for me. I'll take a look at my project setup. Thanks for your help.

**Comment by MasterMahariel** [comment] 2021-03-25 01:45
Sorry to resurrect this issue again but today I am noticing that my `figmagicFolder`, `outputFolderTokens`, and `outputFolderElements` are being ignored. It was working fine yesterday. Was there a change?

**Comment by mikaelvesavuori** [comment] 2021-03-25 08:13
I am not seeing this issue... See image and how it creates folders and files as needed.

<img width="865" alt="figmagic-generation" src="https://user-images.githubusercontent.com/23580994/112440008-14250980-8d4a-11eb-9fe1-a384cf1e925b.png">

**Comment by MasterMahariel** [comment] 2021-03-31 04:22
Sorry for the delay; the issue seems to be resolved now.

**Comment by MasterMahariel** [comment] 2021-03-31 04:34
Here is an example.

![Screenshot (23)](https://user-images.githubusercontent.com/12755283/113090893-cc263c80-91b8-11eb-8a2b-269fde2fda60.png)

It was working a few minutes ago but then it stopped.

**Comment by MasterMahariel** [comment] 2021-03-31 04:56
After looking into this more, there seems to be an issue with where the setting is placed.
 
https://user-images.githubusercontent.com/12755283/113092288-b9613700-91bb-11eb-9211-936c0f86e42a.mp4

**Comment by mikaelvesavuori** [comment] 2021-03-31 06:11
Hi again @MasterMahariel !

Very good reproducible videos. The error is because the document (or just the last item...?) becomes invalid when you have the last semicolon on `"syncElements": true,` and all other such test cases you show.

Removing the last semicolon rectifies the issue. I will close this, and will add a backlog item to see if I can support JSON documents as well, since something like VS Code will usually clean any such messes up.

**Closed by mikaelvesavuori** 2021-03-31 06:11 UTC

**Comment by MasterMahariel** [comment] 2021-04-01 03:45
> Hi again @MasterMahariel !
> 
> Very good reproducible videos. The error is because the document (or just the last item...?) becomes invalid when you have the last semicolon on `"syncElements": true,` and all other such test cases you show.
> 
> Removing the last semicolon rectifies the issue. I will close this, and will add a backlog item to see if I can support JSON documents as well, since something like VS Code will usually clean any such messes up (which will not happen with the current non-standard figmagicrc file).

Thanks for pointing that out. Wow, not sure if I'm happy or mad about it being just a comma issue. At least i'm not ~~going~~ becoming more crazy.
